version: '3.9'

services:
  base:
    build:
      context: ../..
      dockerfile: Dockerfile
    image: lane-autonomy-base
    container_name: lane_autonomy_base
    volumes:
      - ../..:/app
    working_dir: /app
    networks:
      - autonomy_net

  image_acquisition:
    image: lane-autonomy-base
    container_name: image_acquisition
    command: python3 image_acquisition.py
    depends_on:
      - base
    networks:
      - autonomy_net

  preprocessing:
    image: lane-autonomy-base
    container_name: preprocessing
    command: python3 preprocessing.py
    depends_on:
      - image_acquisition
    networks:
      - autonomy_net

networks:
  autonomy_net:
    driver: bridge
