version: '3.9'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: lane-autonomy-base
    container_name: lane_autonomy_base
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - autonomy_net

  image_acquisition:
    image: lane-autonomy-base
    container_name: image_acquisition
    command: python3 image_acquisition.py
    devices:
      - "/dev/video0:/dev/video0" # Replace as needed for Pi Camera
    depends_on:
      - base
    networks:
      - autonomy_net

  preprocessing:
    image: lane-autonomy-base
    container_name: preprocessing
    command: python3 preprocessing.py
    depends_on:
      - image_acquisition
    networks:
      - autonomy_net

  lane_detection:
    image: lane-autonomy-base
    container_name: lane_detection
    command: python3 lane_detection.py
    depends_on:
      - preprocessing
    networks:
      - autonomy_net

  object_detection:
    image: lane-autonomy-base
    container_name: object_detection
    command: python3 object_detection.py
    depends_on:
      - preprocessing
    networks:
      - autonomy_net

  path_planning:
    image: lane-autonomy-base
    container_name: path_planning
    command: python3 path_planning.py
    depends_on:
      - lane_detection
      - object_detection
    networks:
      - autonomy_net

  control_module:
    image: lane-autonomy-base
    container_name: control_module
    command: python3 control_module.py
    depends_on:
      - path_planning
    networks:
      - autonomy_net
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # Adjust serial port as needed

networks:
  autonomy_net:
    driver: bridge
